### PR TITLE
Update to Bevy 0.10

### PR DESCRIPTION
**Pull request by soerenmeier**
I think everything should be working as in the previous version but I haven't used this crate myself.

### CODE REVIEW

**Comment by faulesocke** [comment]
You've added windows line endings. You should probably check your git configuration.

**Comment by soerenmeier** [comment]
Since the last force push they should be gone. Some bug with sublime merge.

**Review by alice-i-cecile — APPROVED** [review]
This migration appears to be done correctly :) Testing this out in https://github.com/Leafwing-Studios/Emergence/pull/500

**Comment by faulesocke** [comment]
Ah interesting, I got fooled by git. All files are with Windows line-endings but `git show` only shows them in the lines that were added, not in removed or untouched lines.

Also played around with the module a bit and it seems to work just fine with 0.10!

**Review by Malax — APPROVED** [review]
I've been using this branch for some days now and it just worked for me :)

**Comment by dimvoly** [comment]
In `lib.rs` on lines 410 and 412, you'd want to cover the case where the entity is visible, but visibility is not inherited:

```
if let RaycastMethod::Screenspace(_) = pick_source.cast_method {
	(visibility == Visibility::Inherited && comp_visibility.is_visible())
	||
	(visibility == Visibility::Visible && comp_visibility.is_visible())
	} else {
	visibility == Visibility::Inherited
	||
	visibility == Visibility::Visible
};
```

As it is now, it's possible to end up with visible entities that you don't raycast to (and therefore can't pick via `bevy_mod_picking` in my use case).

**Comment by soerenmeier** [comment]
You're right, I wen't with the [migration guide](https://bevyengine.org/learn/migration-guides/0.9-0.10/#enum-visibility-component) but it makes more sense, to take into account `Visibility::Visible`.
I took the liberty to remove manually checking Visibility since that is already done in the `visibility_propagate_system` of bevy and now rely on `ComputedVisibility`.

**Comment by luke-biel** [comment]
@aevyrie any chance this gets merged?

**Comment by aevyrie** [comment]
Thanks @soerenmeier for your effort here, and everyone else for your patience. ❤️

**Pull request merged**
